ORDER_NEW = "nieuw"
ORDER_CHECKED = "gecontroleerd"
ORDER_FULLY_FROM_INVENTORY = "volledig_uit_voorraad"
ORDER_PARTLY_TO_PRINT = "deels_te_printen"
ORDER_FULLY_TO_PRINT = "volledig_te_printen"
ORDER_PLANNED = "ingepland"
ORDER_PRINTED = "geprint"
ORDER_POST_PROCESSING = "nabewerking"
ORDER_PACKED = "ingepakt"
ORDER_SHIPPED = "verzonden"
ORDER_CANCELLED = "geannuleerd"

INVENTORY_FULL = "volledig_op_voorraad"
INVENTORY_PARTIAL = "deels_op_voorraad"
INVENTORY_NONE = "niet_op_voorraad"

PRINT_JOB_NEW = "nieuw"
PRINT_JOB_PLANNED = "gepland"
PRINT_JOB_PRINTING = "bezig"
PRINT_JOB_PRINTED = "geprint"
PRINT_JOB_PARTLY_FAILED = "deels_mislukt"
PRINT_JOB_FAILED = "mislukt"
PRINT_JOB_PROCESSED = "verwerkt"
PRINT_JOB_CANCELLED = "geannuleerd"

PUBLICATION_NOT_PUBLISHED = "niet_gepubliceerd"
PUBLICATION_CONCEPT = "concept"
PUBLICATION_READY = "klaar_voor_publicatie"
PUBLICATION_PUBLISHED = "gepubliceerd"
PUBLICATION_SYNC_NEEDED = "synchronisatie_nodig"
PUBLICATION_ERROR = "fout"
PUBLICATION_PAUSED = "gepauzeerd"
PUBLICATION_ARCHIVED = "gearchiveerd"

ACCOUNTING_CONCEPT = "concept"
ACCOUNTING_BOOKED = "geboekt"
ACCOUNTING_PAID = "betaald"
ACCOUNTING_CANCELLED = "geannuleerd"
ACCOUNTING_CORRECTED = "gecorrigeerd"
ACCOUNTING_CLOSED = "afgesloten"
ACCOUNTING_DOCUMENT_STORED = "bewaard"
ACCOUNTING_DOCUMENT_ARCHIVED = "gearchiveerd"

RECOMMENDATION_NEW = "nieuw"
RECOMMENDATION_ACCEPTED = "geaccepteerd"
RECOMMENDATION_ADJUSTED = "aangepast"
RECOMMENDATION_IGNORED = "genegeerd"
RECOMMENDATION_CONVERTED = "omgezet_naar_printtaak"
